# Generated by Django 5.1.3 on 2024-12-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='business_user',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_user',
            field=models.CharField(default='', max_length=100),
        ),
    ]
