# Generated by Django 5.1.3 on 2024-12-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='user',
            field=models.CharField(default='', max_length=100),
        ),
    ]
