# Generated by Django 5.1.3 on 2024-12-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0002_alter_offer_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='offerdetail',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='revisions',
            field=models.IntegerField(),
        ),
    ]
