# Generated by Django 5.1.3 on 2024-12-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0003_alter_offerdetail_unique_together_alter_offer_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(default='', upload_to='profile_pictures/'),
        ),
    ]
