# Generated by Django 5.1.3 on 2024-12-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0005_alter_offer_image_alter_offer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(default='', upload_to='profile_pictures/'),
        ),
    ]
