# Generated by Django 5.1.3 on 2024-12-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0009_remove_offerdetail_offer_offer_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='details',
        ),
        migrations.AddField(
            model_name='offer',
            name='details',
            field=models.JSONField(default=list),
        ),
    ]
