# Generated by Django 5.1.3 on 2024-12-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0010_remove_offer_details_offer_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='details',
        ),
        migrations.AddField(
            model_name='offer',
            name='details',
            field=models.ManyToManyField(to='offers_app.offerdetail'),
        ),
    ]
