# Generated by Django 5.1.3 on 2024-12-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0014_alter_offer_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='details',
        ),
        migrations.AddField(
            model_name='offer',
            name='details',
            field=models.JSONField(default=list),
        ),
    ]
