# Generated by Django 5.1.3 on 2024-12-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0015_remove_offer_details_offer_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='delivery_time_in_days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='features',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='offer_type',
            field=models.CharField(max_length=100),
        ),
    ]
