# Generated by Django 5.1.3 on 2024-12-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0016_alter_offerdetail_delivery_time_in_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='features',
            field=models.JSONField(),
        ),
    ]
