# Generated by Django 5.1.3 on 2024-12-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0018_remove_offer_details_offer_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='details',
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(default='', upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='features',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='offer',
            name='details',
            field=models.JSONField(default=list),
        ),
    ]
