# Generated by Django 5.1.3 on 2024-12-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0020_alter_offer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='details',
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(default='', upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='delivery_time_in_days',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='features',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='offer_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=20),
        ),
        migrations.AddField(
            model_name='offer',
            name='details',
            field=models.ManyToManyField(to='offers_app.offerdetail'),
        ),
    ]
