# Generated by Django 5.1.3 on 2024-12-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0022_alter_offer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='revisions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
