# Generated by Django 5.1.3 on 2024-12-15 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0026_alter_offer_min_delivery_time_alter_offer_min_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='user_details',
        ),
    ]
