# Generated by Django 5.1.3 on 2024-12-15 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0028_offer_user_details_alter_offer_min_delivery_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='min_delivery_time',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='user_details',
        ),
    ]
