# Generated by Django 5.1.3 on 2024-12-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0030_offer_min_delivery_time_offer_user_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='min_delivery_time',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='offer',
            name='min_price',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='offer',
            name='user_details',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
