# Generated by Django 5.1.3 on 2024-12-15 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0032_offer_user_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='user_data',
        ),
    ]
