# Generated by Django 5.1.3 on 2024-12-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0033_remove_offer_user_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerdetail',
            name='user',
            field=models.CharField(default='', max_length=100),
        ),
    ]
