# Generated by Django 5.1.3 on 2024-12-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0034_offerdetail_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='details',
        ),
        migrations.AlterField(
            model_name='offer',
            name='user',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='user',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='offer',
            name='details',
            field=models.ManyToManyField(related_name='offers', to='offers_app.offerdetail'),
        ),
    ]
