# Generated by Django 5.1.3 on 2024-12-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0036_alter_offer_user_alter_offerdetail_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='details',
        ),
        migrations.AlterField(
            model_name='offer',
            name='user',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='user',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='offer',
            name='details',
            field=models.JSONField(default=list),
        ),
    ]
