# Generated by Django 5.1.3 on 2024-12-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0037_remove_offer_details_alter_offer_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='user',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='user',
            field=models.IntegerField(default=2),
        ),
    ]
