# Generated by Django 5.1.3 on 2024-12-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0038_alter_offer_user_alter_offerdetail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='max_delivery_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='min_delivery_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
