# Generated by Django 5.1.3 on 2024-12-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0043_alter_offer_min_price_alter_offer_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
