# Generated by Django 5.1.3 on 2024-12-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0045_alter_offerdetail_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
