# Generated by Django 5.1.3 on 2024-12-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0046_alter_offerdetail_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='price',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
