# Generated by Django 5.1.3 on 2024-12-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0052_alter_offer_min_price_alter_offerdetail_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='price',
            field=models.PositiveIntegerField(blank=True, max_length=255),
        ),
    ]
