# Generated by Django 5.1.3 on 2024-12-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0066_alter_offer_min_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
