# Generated by Django 5.1.3 on 2024-12-08 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0004_rename_created_at_profile_uploaded_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='uploaded_at',
            new_name='created_at',
        ),
    ]
