# Generated by Django 5.1.3 on 2024-12-08 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0006_profile_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
