# Generated by Django 5.1.3 on 2024-12-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0012_alter_profile_description_alter_profile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='file',
            field=models.ImageField(default='', upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tel',
            field=models.CharField(default='', max_length=20),
        ),
    ]
