# Generated by Django 5.1.3 on 2024-12-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0013_alter_profile_file_alter_profile_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=' ', max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='file',
            field=models.ImageField(default=' ', upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tel',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='working_hours',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
