# Generated by Django 5.1.3 on 2024-12-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0015_alter_profile_email_alter_profile_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.JSONField(blank=True, default=list)),
                ('file', models.ImageField(default='', upload_to='profile_pictures/')),
                ('location', models.CharField(default='', max_length=255)),
                ('tel', models.CharField(default='', max_length=20)),
                ('description', models.TextField(default=' ')),
                ('working_hours', models.CharField(default='', max_length=50)),
                ('type', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.JSONField(blank=True, default=list)),
                ('file', models.ImageField(default='', upload_to='profile_pictures/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
