# Generated by Django 5.1.3 on 2024-12-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0016_profilebusiness_profilecustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
