# Generated by Django 5.1.3 on 2024-12-17 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0017_profileuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileBusiness',
        ),
        migrations.DeleteModel(
            name='ProfileCustomer',
        ),
        migrations.DeleteModel(
            name='ProfileUser',
        ),
    ]
