# Generated by Django 5.1.3 on 2024-12-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0002_alter_review_business_user_alter_review_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='business_user',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.IntegerField(),
        ),
    ]
